//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcusticGuitar : Guitar
    {
        public AcusticGuitar()
        {
            this.MaterialAcustic = new AcusticGuitarMaterial();
        }
    
        public string Pickup { get; set; }
    
        public AcusticGuitarMaterial MaterialAcustic { get; set; }
    }
}
