//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcusticDrum : Product
    {
        public string Seria { get; set; }
        public Nullable<int> DrumQuantity { get; set; }
        public string BassDrum { get; set; }
        public string FloorTom { get; set; }
        public string FirstTom { get; set; }
        public string SecondTom { get; set; }
        public string SnareDrum { get; set; }
        public string Set { get; set; }
        public string Material { get; set; }
    }
}
