//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    
    public partial class AcusticGuitarMaterial
    {
        public string TopDeka { get; set; }
        public string BottomDeka { get; set; }
        public string Neck { get; set; }
        public string NeckCover { get; set; }
        public string Bridge { get; set; }
    }
}
