//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Delivary = new HashSet<Delivary>();
        }
    
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public Nullable<int> Apartment { get; set; }
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual ICollection<Delivary> Delivary { get; set; }
        public virtual User User { get; set; }
    }
}
