//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivary
    {
        public Nullable<decimal> Cost { get; set; }
        public int Address_Id { get; set; }
        public int Order_Id { get; set; }
    
        public virtual Order order { get; set; }
        public virtual Address Address { get; set; }
    }
}
