//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    
    public partial class ElectroAndBassGuitarMaterial
    {
        public string BodyMaterial { get; set; }
        public string NeckMaterial { get; set; }
        public string NeckCoverMaterial { get; set; }
    }
}
