//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    
    public partial class ElectroDrumConfiguration
    {
        public string Peds { get; set; }
        public string Cembals { get; set; }
        public string Pedals { get; set; }
        public string Racks { get; set; }
    }
}
