//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectroDrum : Product
    {
        public ElectroDrum()
        {
            this.Configuration = new ElectroDrumConfiguration();
            this.Tembers = new ElectroDrumTembers();
        }
    
        public string Inputs { get; set; }
        public string Outputs { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
    
        public ElectroDrumConfiguration Configuration { get; set; }
        public ElectroDrumTembers Tembers { get; set; }
    }
}
