//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    
    public partial class ElectroAndBassGuitarConstruction
    {
        public string NeckMount { get; set; }
        public string NeckSideView { get; set; }
        public Nullable<bool> StringsThroughtBody { get; set; }
    }
}
