//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    
    public partial class GeneralAttributes
    {
        public string Name { get; set; }
        public string Desribtion { get; set; }
        public Nullable<int> Guaranty { get; set; }
        public decimal Price { get; set; }
        public int Reiting { get; set; }
        public bool IsNew { get; set; }
    }
}
