//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guitar : Product
    {
        public Guitar()
        {
            this.Construction = new GuitarConstruction();
            this.Material = new GuitarMaterial();
        }
    
        public string Set { get; set; }
    
        public GuitarConstruction Construction { get; set; }
        public GuitarMaterial Material { get; set; }
    }
}
