//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    
    public partial class GuitarConstruction
    {
        public GuitarConstruction()
        {
            this.StringQuantity = 6;
        }
    
        public Nullable<int> StringQuantity { get; set; }
        public Nullable<int> FretQuantity { get; set; }
        public string Size { get; set; }
    }
}
