//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyboard : Product
    {
        public Keyboard()
        {
            this.Keys = new KeyboardKeys();
            this.Tembers = new KeyboardTembers();
            this.Effects = new KeyboardEffects();
            this.GeneralKb = new KeyboardGeneral();
        }
    
        public Nullable<bool> HasAutoAccompaniment { get; set; }
        public string Inputs { get; set; }
        public string Outputs { get; set; }
    
        public KeyboardKeys Keys { get; set; }
        public KeyboardTembers Tembers { get; set; }
        public KeyboardEffects Effects { get; set; }
        public KeyboardGeneral GeneralKb { get; set; }
    }
}
