//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    
    public partial class KeyboardKeys
    {
        public Nullable<bool> HasLighting { get; set; }
        public Nullable<sbyte> LevelTouchQuantity { get; set; }
        public Nullable<int> KeyQuantity { get; set; }
        public string KeyMachanic { get; set; }
        public string KeyType { get; set; }
    }
}
