//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public int Customer_Id { get; set; }
        public int PaymentTypes_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual PaymentType paymenttypes { get; set; }
        public virtual ICollection<Product> product { get; set; }
        public virtual Delivary delivary { get; set; }
        public virtual User user { get; set; }
    }
}
