//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.order = new HashSet<Order>();
            this.General = new GeneralAttributes();
        }
    
        public int Id { get; set; }
        public string ExtraProperties { get; set; }
        public int Category_Id { get; set; }
        public string Image_path { get; set; }
        public int Producer_Id { get; set; }
        public int Color_Id { get; set; }
    
        public GeneralAttributes General { get; set; }
    
        public virtual ICollection<Order> order { get; set; }
        public virtual productcategory productcategory { get; set; }
        public virtual Color color { get; set; }
        public virtual Producer producer { get; set; }
    }
}
