//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Synthesizer : Keyboard
    {
        public Synthesizer()
        {
            this.KeySz = new SynthesizerKeys();
            this.AutoAccompaniment = new SynthesizerAutoAccomponiment();
        }
    
        public string ToneGenerator { get; set; }
        public string Sempling { get; set; }
        public string Sequence { get; set; }
    
        public SynthesizerKeys KeySz { get; set; }
        public SynthesizerAutoAccomponiment AutoAccompaniment { get; set; }
    }
}
